### ISSUE TITLE
docker以及docker-compose中再次启动失败

### ISSUE THREAD

**Issue by akaQin** [swoft-cloud/swoft#693]
第一次`docker-compose up`正常启动，`Ctrl+C`停掉后再次启动，会报下面的错误，只有把`runtime/swoft.pid`文件删掉才能再次启动
```
Creating network "swoft_default" with the default driver
Creating swoft ... done
Attaching to swoft
swoft    | The HTTP server have been running!(PID: 1)
```

__Dockerfile__:
```
FROM php:7.2

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# install PHP extensions

RUN apt-get update --fix-missing \
    && apt-get install -y --fix-missing \
      curl \
      vim \
      git \
      zip \
      wget \
      libz-dev \
      libssl-dev \
      libpcre3-dev \
      libnghttp2-dev \
    && apt-get clean \
    && apt-get autoremove \
    && docker-php-ext-install bcmath \
    && docker-php-ext-install sockets \
    && docker-php-ext-install pdo_mysql \
    && pecl install -o -f redis \
    && docker-php-ext-enable redis \
    && rm -rf /tmp/*


# Hiredis
RUN wget https://github.com/redis/hiredis/archive/v0.14.0.tar.gz -O hiredis.tar.gz \
    && mkdir -p hiredis \
    && tar -xf hiredis.tar.gz -C hiredis --strip-components=1 \
    && rm hiredis.tar.gz \
    && ( \
        cd hiredis \
        && make -j$(nproc) \
        && make install \
        && ldconfig \
    ) \
    && rm -r hiredis


# Swoole extension
RUN wget https://github.com/swoole/swoole-src/archive/v4.3.4.tar.gz -O swoole.tar.gz \
    && mkdir -p swoole \
    && tar -xf swoole.tar.gz -C swoole --strip-components=1 \
    && rm swoole.tar.gz \
    && ( \
    cd swoole \
    && phpize \
    && ./configure --enable-async-redis --enable-mysqlnd --enable-openssl --enable-http2 \
    && make -j$(nproc) \
    && make install \
    ) \
    && rm -r swoole \
    && docker-php-ext-enable swoole


# Composer
#RUN curl -sS https://getcomposer.org/installer | php \
#    && mv composer.phar /usr/local/bin/composer \
#    && composer config -g repo.packagist composer https://packagist.phpcomposer.com \
#    && composer self-update --clean-backups


WORKDIR /var/www/html/swoft/

CMD ["php", "bin/swoft", "http:start"]
```
__docker-compose.yml__:
```
version: "3"
services:
  swoft:
    container_name: swoft
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18306:18306"
    volumes:
      - /Users/qinlong/hbh/swoft:/var/www/html/swoft/:rw

    restart: unless-stopped
    networks:
      - default

networks:
  default:
```
